export const cities = [
  // Major world cities (expanded to 300+)
  { name: "Tokyo", country: "Japan", timeZone: "Asia/Tokyo" },
  { name: "Delhi", country: "India", timeZone: "Asia/Kolkata" },
  { name: "Shanghai", country: "China", timeZone: "Asia/Shanghai" },
  { name: "São Paulo", country: "Brazil", timeZone: "America/Sao_Paulo" },
  { name: "Mexico City", country: "Mexico", timeZone: "America/Mexico_City" },
  { name: "Cairo", country: "Egypt", timeZone: "Africa/Cairo" },
  { name: "Mumbai", country: "India", timeZone: "Asia/Kolkata" },
  { name: "Beijing", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Dhaka", country: "Bangladesh", timeZone: "Asia/Dhaka" },
  { name: "Osaka", country: "Japan", timeZone: "Asia/Tokyo" },
  { name: "New York", country: "USA", timeZone: "America/New_York" },
  { name: "Karachi", country: "Pakistan", timeZone: "Asia/Karachi" },
  { name: "Buenos Aires", country: "Argentina", timeZone: "America/Argentina/Buenos_Aires" },
  { name: "Chongqing", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Istanbul", country: "Turkey", timeZone: "Europe/Istanbul" },
  { name: "Kolkata", country: "India", timeZone: "Asia/Kolkata" },
  { name: "Manila", country: "Philippines", timeZone: "Asia/Manila" },
  { name: "Lagos", country: "Nigeria", timeZone: "Africa/Lagos" },
  { name: "Rio de Janeiro", country: "Brazil", timeZone: "America/Sao_Paulo" },
  { name: "Tianjin", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Kinshasa", country: "DR Congo", timeZone: "Africa/Kinshasa" },
  { name: "Guangzhou", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Los Angeles", country: "USA", timeZone: "America/Los_Angeles" },
  { name: "Moscow", country: "Russia", timeZone: "Europe/Moscow" },
  { name: "Shenzhen", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Lahore", country: "Pakistan", timeZone: "Asia/Karachi" },
  { name: "Bangalore", country: "India", timeZone: "Asia/Kolkata" },
  { name: "Paris", country: "France", timeZone: "Europe/Paris" },
  { name: "Bogotá", country: "Colombia", timeZone: "America/Bogota" },
  { name: "Jakarta", country: "Indonesia", timeZone: "Asia/Jakarta" },
  { name: "Chennai", country: "India", timeZone: "Asia/Kolkata" },
  { name: "Lima", country: "Peru", timeZone: "America/Lima" },
  { name: "Bangkok", country: "Thailand", timeZone: "Asia/Bangkok" },
  { name: "Seoul", country: "South Korea", timeZone: "Asia/Seoul" },
  { name: "Nagoya", country: "Japan", timeZone: "Asia/Tokyo" },
  { name: "Hyderabad", country: "India", timeZone: "Asia/Kolkata" },
  { name: "London", country: "UK", timeZone: "Europe/London" },
  { name: "Tehran", country: "Iran", timeZone: "Asia/Tehran" },
  { name: "Chicago", country: "USA", timeZone: "America/Chicago" },
  { name: "Chengdu", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Nanjing", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Wuhan", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Ho Chi Minh City", country: "Vietnam", timeZone: "Asia/Ho_Chi_Minh" },
  { name: "Luanda", country: "Angola", timeZone: "Africa/Luanda" },
  { name: "Ahmedabad", country: "India", timeZone: "Asia/Kolkata" },
  { name: "Kuala Lumpur", country: "Malaysia", timeZone: "Asia/Kuala_Lumpur" },
  { name: "Xi'an", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Hong Kong", country: "China", timeZone: "Asia/Hong_Kong" },
  { name: "Dongguan", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Hangzhou", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Foshan", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Shenyang", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Riyadh", country: "Saudi Arabia", timeZone: "Asia/Riyadh" },
  { name: "Baghdad", country: "Iraq", timeZone: "Asia/Baghdad" },
  { name: "Santiago", country: "Chile", timeZone: "America/Santiago" },
  { name: "Surat", country: "India", timeZone: "Asia/Kolkata" },
  { name: "Madrid", country: "Spain", timeZone: "Europe/Madrid" },
  { name: "Suzhou", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Pune", country: "India", timeZone: "Asia/Kolkata" },
  { name: "Harbin", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Houston", country: "USA", timeZone: "America/Chicago" },
  { name: "Dallas", country: "USA", timeZone: "America/Chicago" },
  { name: "Toronto", country: "Canada", timeZone: "America/Toronto" },
  { name: "Dar es Salaam", country: "Tanzania", timeZone: "Africa/Dar_es_Salaam" },
  { name: "Miami", country: "USA", timeZone: "America/New_York" },
  { name: "Belo Horizonte", country: "Brazil", timeZone: "America/Sao_Paulo" },
  { name: "Singapore", country: "Singapore", timeZone: "Asia/Singapore" },
  { name: "Philadelphia", country: "USA", timeZone: "America/New_York" },
  { name: "Atlanta", country: "USA", timeZone: "America/New_York" },
  { name: "Fukuoka", country: "Japan", timeZone: "Asia/Tokyo" },
  { name: "Khartoum", country: "Sudan", timeZone: "Africa/Khartoum" },
  { name: "Barcelona", country: "Spain", timeZone: "Europe/Madrid" },
  { name: "Johannesburg", country: "South Africa", timeZone: "Africa/Johannesburg" },
  { name: "Saint Petersburg", country: "Russia", timeZone: "Europe/Moscow" },
  { name: "Qingdao", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Dalian", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Washington DC", country: "USA", timeZone: "America/New_York" },
  { name: "Yangon", country: "Myanmar", timeZone: "Asia/Yangon" },
  { name: "Alexandria", country: "Egypt", timeZone: "Africa/Cairo" },
  { name: "Jinan", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Guadalajara", country: "Mexico", timeZone: "America/Mexico_City" },
  { name: "Ankara", country: "Turkey", timeZone: "Europe/Istanbul" },
  { name: "Zhengzhou", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Monterrey", country: "Mexico", timeZone: "America/Monterrey" },
  { name: "Changsha", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Brasília", country: "Brazil", timeZone: "America/Sao_Paulo" },
  { name: "Jiddah", country: "Saudi Arabia", timeZone: "Asia/Riyadh" },
  { name: "Urumqi", country: "China", timeZone: "Asia/Urumqi" },
  { name: "Kunming", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Changchun", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Hefei", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Shantou", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Xinbei", country: "Taiwan", timeZone: "Asia/Taipei" },
  { name: "Kabul", country: "Afghanistan", timeZone: "Asia/Kabul" },
  { name: "Ningbo", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Tel Aviv", country: "Israel", timeZone: "Asia/Jerusalem" },
  { name: "Hanoi", country: "Vietnam", timeZone: "Asia/Ho_Chi_Minh" },
  { name: "Taiyuan", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Kharkiv", country: "Ukraine", timeZone: "Europe/Kiev" },
  { name: "Durban", country: "South Africa", timeZone: "Africa/Johannesburg" },
  { name: "Jaipur", country: "India", timeZone: "Asia/Kolkata" },
  { name: "Berlin", country: "Germany", timeZone: "Europe/Berlin" },
  { name: "Tangshan", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Zhongshan", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Casablanca", country: "Morocco", timeZone: "Africa/Casablanca" },
  { name: "Wuxi", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Shijiazhuang", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Recife", country: "Brazil", timeZone: "America/Recife" },
  { name: "Boston", country: "USA", timeZone: "America/New_York" },
  { name: "Phoenix", country: "USA", timeZone: "America/Phoenix" },
  { name: "Fortaleza", country: "Brazil", timeZone: "America/Fortaleza" },
  { name: "Lucknow", country: "India", timeZone: "Asia/Kolkata" },
  { name: "Porto Alegre", country: "Brazil", timeZone: "America/Sao_Paulo" },
  { name: "Nanning", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Wenzhou", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Zibo", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Fuzhou", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Kanpur", country: "India", timeZone: "Asia/Kolkata" },
  { name: "Izmir", country: "Turkey", timeZone: "Europe/Istanbul" },
  { name: "Taichung", country: "Taiwan", timeZone: "Asia/Taipei" },
  { name: "Medellin", country: "Colombia", timeZone: "America/Bogota" },
  { name: "Algiers", country: "Algeria", timeZone: "Africa/Algiers" },
  { name: "Abidjan", country: "Ivory Coast", timeZone: "Africa/Abidjan" },
  { name: "Busan", country: "South Korea", timeZone: "Asia/Seoul" },
  { name: "Cape Town", country: "South Africa", timeZone: "Africa/Johannesburg" },
  { name: "Taipei", country: "Taiwan", timeZone: "Asia/Taipei" },
  { name: "Jilin", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Bandung", country: "Indonesia", timeZone: "Asia/Jakarta" },
  { name: "Xiamen", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Hyderabad", country: "Pakistan", timeZone: "Asia/Karachi" },
  { name: "Douala", country: "Cameroon", timeZone: "Africa/Douala" },
  { name: "Bucharest", country: "Romania", timeZone: "Europe/Bucharest" },
  { name: "Curitiba", country: "Brazil", timeZone: "America/Sao_Paulo" },
  { name: "Nanchang", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Kozhikode", country: "India", timeZone: "Asia/Kolkata" },
  { name: "Guiyang", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Salvador", country: "Brazil", timeZone: "America/Bahia" },
  { name: "Lanzhou", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Incheon", country: "South Korea", timeZone: "Asia/Seoul" },
  { name: "Huizhou", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Coimbatore", country: "India", timeZone: "Asia/Kolkata" },
  { name: "Dakar", country: "Senegal", timeZone: "Africa/Dakar" },
  { name: "Vienna", country: "Austria", timeZone: "Europe/Vienna" },
  { name: "Baotou", country: "China", timeZone: "Asia/Shanghai" },
  { name: "Adana", country: "Turkey", timeZone: "Europe/Istanbul" },
  { name: "Quito", country: "Ecuador", timeZone: "America/Guayaquil" },
  { name: "Faisalabad", country: "Pakistan", timeZone: "Asia/Karachi" },
  { name: "Kyiv (Kiev)", country: "Ukraine", timeZone: "Europe/Kiev" },
  { name: "Daegu", country: "South Korea", timeZone: "Asia/Seoul" },
  { name: "Antananarivo", country: "Madagascar", timeZone: "Indian/Antananarivo" },
  { name: "Kano", country: "Nigeria", timeZone: "Africa/Lagos" },
  { name: "Mashhad", country: "Iran", timeZone: "Asia/Tehran" },
  { name: "Caracas", country: "Venezuela", timeZone: "America/Caracas" },
  { name: "Havana", country: "Cuba", timeZone: "America/Havana" },
  { name: "Tashkent", country: "Uzbekistan", timeZone: "Asia/Tashkent" },
  { name: "Sydney", country: "Australia", timeZone: "Australia/Sydney" },
  { name: "Melbourne", country: "Australia", timeZone: "Australia/Melbourne" },
  { name: "Auckland", country: "New Zealand", timeZone: "Pacific/Auckland" },
  { name: "Vancouver", country: "Canada", timeZone: "America/Vancouver" },
  { name: "Montreal", country: "Canada", timeZone: "America/Montreal" },
  { name: "San Francisco", country: "USA", timeZone: "America/Los_Angeles" },
  { name: "Seattle", country: "USA", timeZone: "America/Los_Angeles" },
  { name: "Denver", country: "USA", timeZone: "America/Denver" },
  { name: "Amsterdam", country: "Netherlands", timeZone: "Europe/Amsterdam" },
  { name: "Brussels", country: "Belgium", timeZone: "Europe/Brussels" },
  { name: "Dublin", country: "Ireland", timeZone: "Europe/Dublin" },
  { name: "Zurich", country: "Switzerland", timeZone: "Europe/Zurich" },
  { name: "Stockholm", country: "Sweden", timeZone: "Europe/Stockholm" },
  { name: "Oslo", country: "Norway", timeZone: "Europe/Oslo" },
  { name: "Copenhagen", country: "Denmark", timeZone: "Europe/Copenhagen" },
  { name: "Helsinki", country: "Finland", timeZone: "Europe/Helsinki" },
  { name: "Prague", country: "Czech Republic", timeZone: "Europe/Prague" },
  { name: "Warsaw", country: "Poland", timeZone: "Europe/Warsaw" },
  { name: "Athens", country: "Greece", timeZone: "Europe/Athens" },
  { name: "Budapest", country: "Hungary", timeZone: "Europe/Budapest" },
  { name: "Lisbon", country: "Portugal", timeZone: "Europe/Lisbon" },
  { name: "Rome", country: "Italy", timeZone: "Europe/Rome" },
  { name: "Hamburg", country: "Germany", timeZone: "Europe/Berlin" },
  { name: "Munich", country: "Germany", timeZone: "Europe/Berlin" },
  { name: "Milan", country: "Italy", timeZone: "Europe/Rome" },
  { name: "Naples", country: "Italy", timeZone: "Europe/Rome" },
  { name: "Turin", country: "Italy", timeZone: "Europe/Rome" },
  { name: "Valencia", country: "Spain", timeZone: "Europe/Madrid" },
  { name: "Seville", country: "Spain", timeZone: "Europe/Madrid" },
  { name: "Zaragoza", country: "Spain", timeZone: "Europe/Madrid" },
  { name: "Marseille", country: "France", timeZone: "Europe/Paris" },
  { name: "Lyon", country: "France", timeZone: "Europe/Paris" },
  { name: "Toulouse", country: "France", timeZone: "Europe/Paris" },
  { name: "Nice", country: "France", timeZone: "Europe/Paris" },
  { name: "Nantes", country: "France", timeZone: "Europe/Paris" },
  { name: "Frankfurt", country: "Germany", timeZone: "Europe/Berlin" },
  { name: "Stuttgart", country: "Germany", timeZone: "Europe/Berlin" },
  { name: "Rotterdam", country: "Netherlands", timeZone: "Europe/Amsterdam" },
  { name: "The Hague", country: "Netherlands", timeZone: "Europe/Amsterdam" },
  { name: "Antwerp", country: "Belgium", timeZone: "Europe/Brussels" },
  { name: "Ghent", country: "Belgium", timeZone: "Europe/Brussels" },
  { name: "Birmingham", country: "UK", timeZone: "Europe/London" },
  { name: "Manchester", country: "UK", timeZone: "Europe/London" },
  { name: "Glasgow", country: "UK", timeZone: "Europe/London" },
  { name: "Liverpool", country: "UK", timeZone: "Europe/London" },
  { name: "Edinburgh", country: "UK", timeZone: "Europe/London" },
  { name: "Bristol", country: "UK", timeZone: "Europe/London" },
  { name: "Belfast", country: "UK", timeZone: "Europe/London" },
  { name: "Gothenburg", country: "Sweden", timeZone: "Europe/Stockholm" },
  { name: "Malmö", country: "Sweden", timeZone: "Europe/Stockholm" },
  { name: "Bergen", country: "Norway", timeZone: "Europe/Oslo" },
  { name: "Aarhus", country: "Denmark", timeZone: "Europe/Copenhagen" },
  { name: "Tampere", country: "Finland", timeZone: "Europe/Helsinki" },
  { name: "Turku", country: "Finland", timeZone: "Europe/Helsinki" },
  { name: "Espoo", country: "Finland", timeZone: "Europe/Helsinki" },
  { name: "Vantaa", country: "Finland", timeZone: "Europe/Helsinki" },
  { name: "Krakow", country: "Poland", timeZone: "Europe/Warsaw" },
  { name: "Lodz", country: "Poland", timeZone: "Europe/Warsaw" },
  { name: "Wroclaw", country: "Poland", timeZone: "Europe/Warsaw" },
  { name: "Poznan", country: "Poland", timeZone: "Europe/Warsaw" },
  { name: "Gdansk", country: "Poland", timeZone: "Europe/Warsaw" },
  { name: "Thessaloniki", country: "Greece", timeZone: "Europe/Athens" },
  { name: "Patras", country: "Greece", timeZone: "Europe/Athens" },
  { name: "Heraklion", country: "Greece", timeZone: "Europe/Athens" },
  { name: "Larissa", country: "Greece", timeZone: "Europe/Athens" },
  { name: "Volos", country: "Greece", timeZone: "Europe/Athens" },
  { name: "Debrecen", country: "Hungary", timeZone: "Europe/Budapest" },
  { name: "Szeged", country: "Hungary", timeZone: "Europe/Budapest" },
  { name: "Miskolc", country: "Hungary", timeZone: "Europe/Budapest" },
  { name: "Pecs", country: "Hungary", timeZone: "Europe/Budapest" },
  { name: "Gyor", country: "Hungary", timeZone: "Europe/Budapest" },
  { name: "Porto", country: "Portugal", timeZone: "Europe/Lisbon" },
  { name: "Braga", country: "Portugal", timeZone: "Europe/Lisbon" },
  { name: "Coimbra", country: "Portugal", timeZone: "Europe/Lisbon" },
  { name: "Funchal", country: "Portugal", timeZone: "Atlantic/Madeira" },
  { name: "Aveiro", country: "Portugal", timeZone: "Europe/Lisbon" },
  { name: "Florence", country: "Italy", timeZone: "Europe/Rome" },
  { name: "Bologna", country: "Italy", timeZone: "Europe/Rome" },
  { name: "Genoa", country: "Italy", timeZone: "Europe/Rome" },
  { name: "Catania", country: "Italy", timeZone: "Europe/Rome" },
  { name: "Bari", country: "Italy", timeZone: "Europe/Rome" },
  { name: "Cologne", country: "Germany", timeZone: "Europe/Berlin" },
  { name: "Düsseldorf", country: "Germany", timeZone: "Europe/Berlin" },
  { name: "Dortmund", country: "Germany", timeZone: "Europe/Berlin" },
  { name: "Essen", country: "Germany", timeZone: "Europe/Berlin" },
  { name: "Leipzig", country: "Germany", timeZone: "Europe/Berlin" },
  { name: "Bremen", country: "Germany", timeZone: "Europe/Berlin" },
  { name: "Dresden", country: "Germany", timeZone: "Europe/Berlin" },
  { name: "Hannover", country: "Germany", timeZone: "Europe/Berlin" },
  { name: "Nuremberg", country: "Germany", timeZone: "Europe/Berlin" },
  { name: "Duisburg", country: "Germany", timeZone: "Europe/Berlin" },

  // Additional major international cities
  { name: "Brisbane", country: "Australia", timeZone: "Australia/Brisbane" },
  { name: "Perth", country: "Australia", timeZone: "Australia/Perth" },
  { name: "Adelaide", country: "Australia", timeZone: "Australia/Adelaide" },
  { name: "Gold Coast", country: "Australia", timeZone: "Australia/Brisbane" },
  { name: "Canberra", country: "Australia", timeZone: "Australia/Sydney" },
  { name: "Wellington", country: "New Zealand", timeZone: "Pacific/Auckland" },
  { name: "Christchurch", country: "New Zealand", timeZone: "Pacific/Auckland" },
  { name: "Hamilton", country: "New Zealand", timeZone: "Pacific/Auckland" },
  { name: "Calgary", country: "Canada", timeZone: "America/Edmonton" },
  { name: "Edmonton", country: "Canada", timeZone: "America/Edmonton" },
  { name: "Ottawa", country: "Canada", timeZone: "America/Toronto" },
  { name: "Quebec City", country: "Canada", timeZone: "America/Toronto" },
  { name: "Winnipeg", country: "Canada", timeZone: "America/Winnipeg" },
  { name: "Halifax", country: "Canada", timeZone: "America/Halifax" },
  { name: "Victoria", country: "Canada", timeZone: "America/Vancouver" },

  // All US States (with major cities if not already listed)
  { name: "Alabama (Birmingham)", country: "USA", timeZone: "America/Chicago" },
  { name: "Alaska (Anchorage)", country: "USA", timeZone: "America/Anchorage" },
  { name: "Arizona (Phoenix)", country: "USA", timeZone: "America/Phoenix" },
  { name: "Arkansas (Little Rock)", country: "USA", timeZone: "America/Chicago" },
  { name: "California (Los Angeles)", country: "USA", timeZone: "America/Los_Angeles" },
  { name: "Colorado (Denver)", country: "USA", timeZone: "America/Denver" },
  { name: "Connecticut (Hartford)", country: "USA", timeZone: "America/New_York" },
  { name: "Delaware (Dover)", country: "USA", timeZone: "America/New_York" },
  { name: "Florida (Miami)", country: "USA", timeZone: "America/New_York" },
  { name: "Georgia (Atlanta)", country: "USA", timeZone: "America/New_York" },
  { name: "Hawaii (Honolulu)", country: "USA", timeZone: "Pacific/Honolulu" },
  { name: "Idaho (Boise)", country: "USA", timeZone: "America/Boise" },
  { name: "Illinois (Chicago)", country: "USA", timeZone: "America/Chicago" },
  { name: "Indiana (Indianapolis)", country: "USA", timeZone: "America/Indiana/Indianapolis" },
  { name: "Iowa (Des Moines)", country: "USA", timeZone: "America/Chicago" },
  { name: "Kansas (Wichita)", country: "USA", timeZone: "America/Chicago" },
  { name: "Kentucky (Louisville)", country: "USA", timeZone: "America/New_York" },
  { name: "Louisiana (New Orleans)", country: "USA", timeZone: "America/Chicago" },
  { name: "Maine (Portland)", country: "USA", timeZone: "America/New_York" },
  { name: "Maryland (Baltimore)", country: "USA", timeZone: "America/New_York" },
  { name: "Massachusetts (Boston)", country: "USA", timeZone: "America/New_York" },
  { name: "Michigan (Detroit)", country: "USA", timeZone: "America/Detroit" },
  { name: "Minnesota (Minneapolis)", country: "USA", timeZone: "America/Chicago" },
  { name: "Mississippi (Jackson)", country: "USA", timeZone: "America/Chicago" },
  { name: "Missouri (Kansas City)", country: "USA", timeZone: "America/Chicago" },
  { name: "Montana (Billings)", country: "USA", timeZone: "America/Denver" },
  { name: "Nebraska (Omaha)", country: "USA", timeZone: "America/Chicago" },
  { name: "Nevada (Las Vegas)", country: "USA", timeZone: "America/Los_Angeles" },
  { name: "New Hampshire (Manchester)", country: "USA", timeZone: "America/New_York" },
  { name: "New Jersey (Newark)", country: "USA", timeZone: "America/New_York" },
  { name: "New Mexico (Albuquerque)", country: "USA", timeZone: "America/Denver" },
  { name: "New York (New York City)", country: "USA", timeZone: "America/New_York" },
  { name: "North Carolina (Charlotte)", country: "USA", timeZone: "America/New_York" },
  { name: "North Dakota (Fargo)", country: "USA", timeZone: "America/Chicago" },
  { name: "Ohio (Columbus)", country: "USA", timeZone: "America/New_York" },
  { name: "Oklahoma (Oklahoma City)", country: "USA", timeZone: "America/Chicago" },
  { name: "Oregon (Portland)", country: "USA", timeZone: "America/Los_Angeles" },
  { name: "Pennsylvania (Philadelphia)", country: "USA", timeZone: "America/New_York" },
  { name: "Rhode Island (Providence)", country: "USA", timeZone: "America/New_York" },
  { name: "South Carolina (Columbia)", country: "USA", timeZone: "America/New_York" },
  { name: "South Dakota (Sioux Falls)", country: "USA", timeZone: "America/Chicago" },
  { name: "Tennessee (Nashville)", country: "USA", timeZone: "America/Chicago" },
  { name: "Texas (Houston)", country: "USA", timeZone: "America/Chicago" },
  { name: "Utah (Salt Lake City)", country: "USA", timeZone: "America/Denver" },
  { name: "Vermont (Burlington)", country: "USA", timeZone: "America/New_York" },
  { name: "Virginia (Virginia Beach)", country: "USA", timeZone: "America/New_York" },
  { name: "Washington (Seattle)", country: "USA", timeZone: "America/Los_Angeles" },
  { name: "West Virginia (Charleston)", country: "USA", timeZone: "America/New_York" },
  { name: "Wisconsin (Milwaukee)", country: "USA", timeZone: "America/Chicago" },
  { name: "Wyoming (Cheyenne)", country: "USA", timeZone: "America/Denver" },

  // Countries with a single time zone
  { name: "Afghanistan", country: "Single Time Zone", timeZone: "Asia/Kabul" },
  { name: "Albania", country: "Single Time Zone", timeZone: "Europe/Tirane" },
  { name: "Andorra", country: "Single Time Zone", timeZone: "Europe/Andorra" },
  { name: "Armenia", country: "Single Time Zone", timeZone: "Asia/Yerevan" },
  { name: "Austria", country: "Single Time Zone", timeZone: "Europe/Vienna" },
  { name: "Bahrain", country: "Single Time Zone", timeZone: "Asia/Bahrain" },
  { name: "Bangladesh", country: "Single Time Zone", timeZone: "Asia/Dhaka" },
  { name: "Belgium", country: "Single Time Zone", timeZone: "Europe/Brussels" },
  { name: "Bhutan", country: "Single Time Zone", timeZone: "Asia/Thimphu" },
  { name: "Bosnia and Herzegovina", country: "Single Time Zone", timeZone: "Europe/Sarajevo" },
  { name: "Bulgaria", country: "Single Time Zone", timeZone: "Europe/Sofia" },
  { name: "Cambodia", country: "Single Time Zone", timeZone: "Asia/Phnom_Penh" },
  { name: "Croatia", country: "Single Time Zone", timeZone: "Europe/Zagreb" },
  { name: "Cuba", country: "Single Time Zone", timeZone: "America/Havana" },
  { name: "Czech Republic", country: "Single Time Zone", timeZone: "Europe/Prague" },
  { name: "Denmark", country: "Single Time Zone", timeZone: "Europe/Copenhagen" },
  { name: "El Salvador", country: "Single Time Zone", timeZone: "America/El_Salvador" },
  { name: "Estonia", country: "Single Time Zone", timeZone: "Europe/Tallinn" },
  { name: "Finland", country: "Single Time Zone", timeZone: "Europe/Helsinki" },
  { name: "Georgia", country: "Single Time Zone", timeZone: "Asia/Tbilisi" },
  { name: "Greece", country: "Single Time Zone", timeZone: "Europe/Athens" },
  { name: "Guatemala", country: "Single Time Zone", timeZone: "America/Guatemala" },
  { name: "Haiti", country: "Single Time Zone", timeZone: "America/Port-au-Prince" },
  { name: "Honduras", country: "Single Time Zone", timeZone: "America/Tegucigalpa" },
  { name: "Hungary", country: "Single Time Zone", timeZone: "Europe/Budapest" },
  { name: "Iceland", country: "Single Time Zone", timeZone: "Atlantic/Reykjavik" },
  { name: "Ireland", country: "Single Time Zone", timeZone: "Europe/Dublin" },
  { name: "Israel", country: "Single Time Zone", timeZone: "Asia/Jerusalem" },
  { name: "Jamaica", country: "Single Time Zone", timeZone: "America/Jamaica" },
  { name: "Japan", country: "Single Time Zone", timeZone: "Asia/Tokyo" },
  { name: "Jordan", country: "Single Time Zone", timeZone: "Asia/Amman" },
  { name: "Kuwait", country: "Single Time Zone", timeZone: "Asia/Kuwait" },
  { name: "Latvia", country: "Single Time Zone", timeZone: "Europe/Riga" },
  { name: "Lebanon", country: "Single Time Zone", timeZone: "Asia/Beirut" },
  { name: "Lithuania", country: "Single Time Zone", timeZone: "Europe/Vilnius" },
  { name: "Luxembourg", country: "Single Time Zone", timeZone: "Europe/Luxembourg" },
  { name: "Macedonia", country: "Single Time Zone", timeZone: "Europe/Skopje" },
  { name: "Malaysia", country: "Single Time Zone", timeZone: "Asia/Kuala_Lumpur" },
  { name: "Malta", country: "Single Time Zone", timeZone: "Europe/Malta" },
  { name: "Moldova", country: "Single Time Zone", timeZone: "Europe/Chisinau" },
  { name: "Monaco", country: "Single Time Zone", timeZone: "Europe/Monaco" },
  { name: "Montenegro", country: "Single Time Zone", timeZone: "Europe/Podgorica" },
  { name: "Morocco", country: "Single Time Zone", timeZone: "Africa/Casablanca" },
  { name: "Netherlands", country: "Single Time Zone", timeZone: "Europe/Amsterdam" },
  { name: "New Zealand", country: "Single Time Zone", timeZone: "Pacific/Auckland" },
  { name: "Nicaragua", country: "Single Time Zone", timeZone: "America/Managua" },
  { name: "North Korea", country: "Single Time Zone", timeZone: "Asia/Pyongyang" },
  { name: "Norway", country: "Single Time Zone", timeZone: "Europe/Oslo" },
  { name: "Oman", country: "Single Time Zone", timeZone: "Asia/Muscat" },
  { name: "Panama", country: "Single Time Zone", timeZone: "America/Panama" },
  { name: "Paraguay", country: "Single Time Zone", timeZone: "America/Asuncion" },
  { name: "Peru", country: "Single Time Zone", timeZone: "America/Lima" },
  { name: "Philippines", country: "Single Time Zone", timeZone: "Asia/Manila" },
  { name: "Poland", country: "Single Time Zone", timeZone: "Europe/Warsaw" },
  { name: "Portugal", country: "Single Time Zone", timeZone: "Europe/Lisbon" },
  { name: "Qatar", country: "Single Time Zone", timeZone: "Asia/Qatar" },
  { name: "Romania", country: "Single Time Zone", timeZone: "Europe/Bucharest" },
  { name: "San Marino", country: "Single Time Zone", timeZone: "Europe/San_Marino" },
  { name: "Saudi Arabia", country: "Single Time Zone", timeZone: "Asia/Riyadh" },
  { name: "Serbia", country: "Single Time Zone", timeZone: "Europe/Belgrade" },
  { name: "Slovakia", country: "Single Time Zone", timeZone: "Europe/Bratislava" },
  { name: "Slovenia", country: "Single Time Zone", timeZone: "Europe/Ljubljana" },
  { name: "South Korea", country: "Single Time Zone", timeZone: "Asia/Seoul" },
  { name: "Sri Lanka", country: "Single Time Zone", timeZone: "Asia/Colombo" },
  { name: "Sweden", country: "Single Time Zone", timeZone: "Europe/Stockholm" },
  { name: "Switzerland", country: "Single Time Zone", timeZone: "Europe/Zurich" },
  { name: "Syria", country: "Single Time Zone", timeZone: "Asia/Damascus" },
  { name: "Taiwan", country: "Single Time Zone", timeZone: "Asia/Taipei" },
  { name: "Thailand", country: "Single Time Zone", timeZone: "Asia/Bangkok" },
  { name: "Tunisia", country: "Single Time Zone", timeZone: "Africa/Tunis" },
  { name: "Turkey", country: "Single Time Zone", timeZone: "Europe/Istanbul" },
  { name: "United Arab Emirates", country: "Single Time Zone", timeZone: "Asia/Dubai" },
  { name: "Uruguay", country: "Single Time Zone", timeZone: "America/Montevideo" },
  { name: "Vatican City", country: "Single Time Zone", timeZone: "Europe/Vatican" },
  { name: "Venezuela", country: "Single Time Zone", timeZone: "America/Caracas" },
  { name: "Vietnam", country: "Single Time Zone", timeZone: "Asia/Ho_Chi_Minh" },
  { name: "Yemen", country: "Single Time Zone", timeZone: "Asia/Aden" },
  { name: "Zimbabwe", country: "Single Time Zone", timeZone: "Africa/Harare" },
]

