export const timeZones = [
  { value: "Pacific/Honolulu", label: "Honolulu (GMT-10)" },
  { value: "America/Anchorage", label: "Anchorage (GMT-9)" },
  { value: "America/Los_Angeles", label: "Los Angeles (GMT-8)" },
  { value: "America/Denver", label: "Denver (GMT-7)" },
  { value: "America/Chicago", label: "Chicago (GMT-6)" },
  { value: "America/New_York", label: "New York (GMT-5)" },
  { value: "America/Halifax", label: "Halifax (GMT-4)" },
  { value: "America/Sao_Paulo", label: "São Paulo (GMT-3)" },
  { value: "Atlantic/South_Georgia", label: "South Georgia (GMT-2)" },
  { value: "Atlantic/Azores", label: "Azores (GMT-1)" },
  { value: "Europe/London", label: "London (GMT+0)" },
  { value: "Europe/Paris", label: "Paris (GMT+1)" },
  { value: "Europe/Helsinki", label: "Helsinki (GMT+2)" },
  { value: "Europe/Moscow", label: "Moscow (GMT+3)" },
  { value: "Asia/Dubai", label: "Dubai (GMT+4)" },
  { value: "Asia/Karachi", label: "Karachi (GMT+5)" },
  { value: "Asia/Dhaka", label: "Dhaka (GMT+6)" },
  { value: "Asia/Bangkok", label: "Bangkok (GMT+7)" },
  { value: "Asia/Singapore", label: "Singapore (GMT+8)" },
  { value: "Asia/Tokyo", label: "Tokyo (GMT+9)" },
  { value: "Australia/Sydney", label: "Sydney (GMT+10)" },
  { value: "Pacific/Auckland", label: "Auckland (GMT+12)" },
]

